# This file is part of the Sylius sandbox application.
# (c) Paweł Jędrzejewski

sandbox_blogger_backend_post_create:
    pattern: /create
    defaults: { _controller: SandboxBloggerBundle:Backend\Post:create }

sandbox_blogger_backend_post_update:
    pattern: /{id}/update
    defaults: { _controller: SandboxBloggerBundle:Backend\Post:update }

sandbox_blogger_backend_post_delete:
    pattern: /{id}/delete
    defaults: { _controller: SandboxBloggerBundle:Backend\Post:delete }

sandbox_blogger_backend_post_list:
    pattern: /
    defaults: { _controller: SandboxBloggerBundle:Backend\Post:list }

sandbox_blogger_backend_post_show:
    pattern: /{id}
    defaults: { _controller: SandboxBloggerBundle:Backend\Post:show }
